import type { FormEvent } from "react";
import { useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import { submitAssignment } from "../../services/learningService";
import "../../styles/StudentDashboard.css";

type LocationState = { courseId?: string; courseTitle?: string; assignmentTitle?: string; deadline?: string };

export default function UploadProjectPage() {
  const { assignmentId } = useParams(); const location = useLocation(); const state = (location.state as LocationState) || {};
  const [file, setFile] = useState<File | null>(null); const [submitted, setSubmitted] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const title = state.assignmentTitle || "Практичне завдання";
  const deadline = state.deadline ? new Intl.DateTimeFormat("uk-UA", { day: "numeric", month: "long" }).format(new Date(state.deadline)) : "Не вказано";
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!assignmentId || !file) return; setLoading(true); setError(""); try { await submitAssignment(assignmentId, file); setSubmitted(true); } catch (reason) { setError((reason as Error).message || "Не вдалося надіслати роботу."); } finally { setLoading(false); } }

  return <div className="std-dash assignment-upload-page"><nav className="learn-breadcrumbs" aria-label="breadcrumb"><Link to="/student">Головна</Link><span>›</span><Link to={assignmentId ? `/student/assignments/${assignmentId}` : "/student/courses"} state={state}>{title}</Link><span>›</span><span className="active">Завантаження роботи</span></nav><div className="assignment-upload-grid"><section><div className="assignment-upload-hero"><span className="std-badge-tag">[ ЗАВАНТАЖЕННЯ ПРОЄКТУ ]</span><h1>Надішліть виконане завдання</h1><p>Завантажте підсумковий файл до завдання «{title}».</p><div className="assignment-meta-chips"><span>1 файл</span><span>{deadline}</span></div></div><h2 className="assignment-files-title">Файл проєкту</h2>{submitted ? <div className="assignment-submitted-box"><h2>Роботу надіслано</h2><p>Ментор отримає файл на перевірку. Після оцінювання результат буде доступний у картці завдання.</p><Link to={assignmentId ? `/student/assignments/${assignmentId}` : "/student"} state={state} className="std-continue-btn">Повернутися до завдання</Link></div> : <form onSubmit={handleSubmit}><label className={`assignment-upload-dropzone ${file ? "has-file" : ""}`} htmlFor="project-file"><input id="project-file" type="file" hidden onChange={(event) => setFile(event.target.files?.[0] || null)} /><span className="assignment-upload-icon">⇩</span><strong>{file ? file.name : "Перетягніть файл сюди"}</strong><span>{file ? `${Math.ceil(file.size / 1024)} КБ` : "або оберіть матеріал на своєму пристрої"}</span><span className="assignment-upload-select">Обрати файл</span></label>{file && <div className="assignment-file-row"><span>FILE</span><div><strong>{file.name}</strong><small>{Math.ceil(file.size / 1024)} КБ · Готово до надсилання</small></div><button type="button" onClick={() => setFile(null)} aria-label="Видалити файл">×</button></div>}{error && <div className="nex-auth-error-box" role="alert">{error}</div>}<div className="assignment-upload-actions"><Link to={assignmentId ? `/student/assignments/${assignmentId}` : "/student"} state={state} className="assignment-outline-link">← Повернутися</Link><button type="submit" className="std-continue-btn" disabled={!file || loading}>{loading ? "Надсилання..." : "Надіслати роботу"} →</button></div></form>}</section><aside className="assignment-upload-sidebar"><span className="std-badge-tag">[ СТАТУС ]</span><h2>Завантаження файлу</h2><div className="assignment-upload-progress"><span style={{ width: file ? "100%" : "0%" }} /></div><p>{file ? "Файл готовий до надсилання" : "Додайте файл, щоб продовжити"}</p><div className="assignment-status-grid"><div><small>Дедлайн</small><strong>{deadline}</strong></div><div><small>Формат</small><strong>1 файл</strong></div></div><hr /><h3>Перед надсиланням</h3><ul><li className={file ? "ready" : ""}>Перевірте вміст файлу</li><li className={file ? "ready" : ""}>Переконайтеся, що обрано правильну версію</li></ul></aside></div></div>;
}
